name: C/C++ CI

on: [push]

jobs:
  build:

    name: ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: sudo apt install build-essential qt5-default
    - name: make
      run: cd QPingSF; qmake QPingSF.pro; make
   
    
# - name: configure
#  run: ./configure
#- name: make
#  run: make
#- name: make test
#  run: make test

            
    
