name: C/C++ CI

on: [push]

jobs:
  build:

    name: ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    # - name: configure
    #  run: ./configure
    #- name: make
    #  run: make
    #- name: make test
    #  run: make test
     - name: make
       run: cd QPingSF
            qmake QPingSF.pro
            make
     - name: run
       run: cd QPingSF
            ./QPingSF
            
    
